# agents/test_agent.py
# The Test Agent acts as the final step of quality assurance in the pipeline.
# It uses deterministic verification to validate the schema and consistency,
# auto-correcting any errors when possible before outputting.

from pydantic import BaseModel, Field
from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool
from config import LLM_MODEL

from tools.report_verifier import verify_report_integrity
from agents.schemas import FinalReport

class ValidationDetails(BaseModel):
    """Details of the validation check performed on the report."""
    schema_check: str = Field(description="Either 'passed' or 'failed'")
    consistency_check: str = Field(description="Either 'passed' or 'failed'")
    warnings: list[str] = Field(default_factory=list, description="List of warnings or minor issues identified.")


class ValidationReportSchema(BaseModel):
    """The final structured output returned by the Test Agent."""
    status: str = Field(description="Either 'success' or 'failed'")
    validation_details: ValidationDetails
    final_report: FinalReport = Field(description="The final, verified, and corrected study pattern report.")


def create_test_agent() -> LlmAgent:
    """
    Creates the Test Agent.

    It reads 'final_report' from session state, runs the deterministic
    validation tool, corrects issues if any are found, and outputs the result.
    """
    return LlmAgent(
        name="test_agent",
        model=LLM_MODEL,
        description=(
            "You are a Quality Assurance and Test Agent. Your job is to verify the "
            "synthesized study report for correctness, completeness, and formatting, "
            "correcting any bugs in the output JSON structure."
        ),
        instruction="""
        You will receive 'final_report' from session state — which is the study report JSON
        generated by the pattern synthesizer agent.

        Step 1: Convert the 'final_report' to a string and call the 'verify_report_integrity' tool.
        Step 2: Inspect the validation results:
           - If 'is_valid' is true, set status to 'success', populate the validation details, and return the report.
           - If 'is_valid' is false, review the list of 'errors'. Use your reasoning to correct the 'final_report' JSON so it adheres to the correct format (e.g. correcting key names, removing placeholder data, or fixing JSON formatting issues).

        If you correct the report, run the tool on the corrected version to verify. If it passes, set status to 'success' and 'warnings' to include details of the corrections made. If it still fails and cannot be fixed, set status to 'failed'.

        Output ONLY a valid JSON matching the requested schema.
        Do not include any explanation text outside the JSON.
        """,
        tools=[FunctionTool(verify_report_integrity)],
        output_schema=ValidationReportSchema,
        output_key="validated_report",
    )
